plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.kotlin.android)
}

android {
    namespace "com.google.android.msdl"
    compileSdk 37

    defaultConfig {
        minSdk 31
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
    kotlinOptions {
        jvmTarget = '21'
    }

    sourceSets {
        main.java.srcDirs = ["src"]
        main.manifest.srcFile "AndroidManifest.xml"
    }
}

dependencies {
    implementation libs.androidx.annotation
}
